In [24]:
import pandas as pd
import datetime
df = pd.read_csv (r'C:\\Users\\kherr\\Downloads\\DataSample2.csv')
print (df)
print(df.dtypes)
duplicate = df[df.duplicated(subset=[' TimeSt','Latitude','Longitude'],keep=False)]
print(duplicate)
print(duplicate.shape)

dataset = df.drop_duplicates(subset=[' TimeSt','Latitude','Longitude'],keep=False,ignore_index=True)
print("Dataset",dataset)
print(dataset.shape)
#newdf1 = df.groupby([' TimeSt','Latitude','Longitude']).first()
#print(newdf1)
#df2 = df.get([' TimeSt'])
#print(df2)
#duplicate = df2[df.duplicated([' TimeSt'])]
#print(duplicate)

           _ID                   TimeSt Country Province              City  \
0      4516516  2017-06-21 00:00:00.143      CA       ON          Waterloo
1      4516547  2017-06-21 18:00:00.193      CA       ON            London
2      4516550  2017-06-21 15:00:00.287      CA       ON            Guelph
3      4516600  2017-06-21 15:00:00.307      CA       ON         Stratford
4      4516613  2017-06-21 15:00:00.497      CA       ON         Stratford
...        ...                      ...     ...      ...               ...
22020  5614801  2017-06-21 12:23:07.880      CA       ON  Saint Catharines
22021  5614888  2017-06-21 08:23:01.793      CA       AB           Calgary
22022  5614909  2017-06-21 00:23:07.903      CA       ON            Whitby
22023  5614912  2017-06-21 11:23:07.953      CA       ON          Oakville
22024  5615006  2017-06-21 17:23:08.033      CA       ON          Oakville

       Latitude  Longitude
0      43.49347  -80.49123
1      42.93990  -81.27090
2      43.57760  -80.22010
3      43.37160  -80.97730
4      43.37160  -80.97730
...         ...        ...
22020  43.16440  -79.24560
22021  51.02093 -114.10621
22022  43.88730  -78.94220
22023  43.49340  -79.71260
22024  43.43090  -79.77670

[22025 rows x 7 columns]
_ID            int64
 TimeSt       object
Country       object
Province      object
City          object
Latitude     float64
Longitude    float64
dtype: object
           _ID                   TimeSt Country Province         City  \
7      4516831  2017-06-21 12:00:00.950      CA       ON       London
12     4517047  2017-06-21 12:00:00.950      CA       ON       London
17     4517303  2017-06-21 03:00:00.287      CA       ON      Windsor
19     4517347  2017-06-21 03:00:00.287      CA       ON      Windsor
32     4518000  2017-06-21 08:00:00.663      CA       ON    Kitchener
...        ...                      ...     ...      ...          ...
22008  5614255  2017-06-21 04:22:54.890      CA       ON      Toronto
22011  5614409  2017-06-21 20:22:53.367      CA       ON  Mississauga
22013  5614486  2017-06-21 04:22:54.890      CA       ON      Toronto
22019  5614760  2017-06-21 08:23:01.793      CA       AB      Calgary
22021  5614888  2017-06-21 08:23:01.793      CA       AB      Calgary

       Latitude  Longitude
7      43.00910  -81.17650
12     43.00910  -81.17650
17     42.29570  -82.95990
19     42.29570  -82.95990
32     43.46760  -80.48470
...         ...        ...
22008  43.70680  -79.39910
22011  43.58730  -79.60760
22013  43.70680  -79.39910
22019  51.02093 -114.10621
22021  51.02093 -114.10621

[4052 rows x 7 columns]
(4052, 7)
Dataset            _ID                   TimeSt Country Province              City  \
0      4516516  2017-06-21 00:00:00.143      CA       ON          Waterloo
1      4516547  2017-06-21 18:00:00.193      CA       ON            London
2      4516550  2017-06-21 15:00:00.287      CA       ON            Guelph
3      4516600  2017-06-21 15:00:00.307      CA       ON         Stratford
4      4516613  2017-06-21 15:00:00.497      CA       ON         Stratford
...        ...                      ...     ...      ...               ...
17968  5614689  2017-06-21 13:23:01.370      CA       ON            London
17969  5614801  2017-06-21 12:23:07.880      CA       ON  Saint Catharines
17970  5614909  2017-06-21 00:23:07.903      CA       ON            Whitby
17971  5614912  2017-06-21 11:23:07.953      CA       ON          Oakville
17972  5615006  2017-06-21 17:23:08.033      CA       ON          Oakville

       Latitude  Longitude
0      43.49347  -80.49123
1      42.93990  -81.27090
2      43.57760  -80.22010
3      43.37160  -80.97730
4      43.37160  -80.97730
...         ...        ...
17968  42.96110  -81.24310
17969  43.16440  -79.24560
17970  43.88730  -78.94220
17971  43.49340  -79.71260
17972  43.43090  -79.77670

[17973 rows x 7 columns]
(17973, 7)

In [39]:
poi = pd.read_csv (r'C:\\Users\\kherr\\Downloads\\POIList.csv')
print (poi)

  POIID   Latitude   Longitude
0  POI1  53.546167 -113.485734
1  POI2  53.546167 -113.485734
2  POI3  45.521629  -73.566024
3  POI4  45.224830  -63.232729

In [58]:
import numpy as np
import math

l=dataset.shape
l=l[0]
m=poi.shape
m=m[0]
print(l,m)
x=np.zeros(2)
y=np.zeros(2)
s="POI"
dataset["POI"]=np.nan
print(dataset)
for i in range(l):
    Dist=np.zeros(4)
    for j in range(m):
        x[0]=dataset["Latitude"][i]
        x[1]=dataset["Longitude"][i]
        y[0]=poi[" Latitude"][j]
        y[1]=poi["Longitude"][j]
        Dist[j]=math.dist(x, y)
    #print(Dist)    
    #min= Dist.min()
    #print(min)
    #print(np.argmin(Dist))
    min=np.argmin(Dist)
    dataset["POI"]=min+1
    
print(dataset)

17973 4
           _ID                   TimeSt Country Province              City  \
0      4516516  2017-06-21 00:00:00.143      CA       ON          Waterloo
1      4516547  2017-06-21 18:00:00.193      CA       ON            London
2      4516550  2017-06-21 15:00:00.287      CA       ON            Guelph
3      4516600  2017-06-21 15:00:00.307      CA       ON         Stratford
4      4516613  2017-06-21 15:00:00.497      CA       ON         Stratford
...        ...                      ...     ...      ...               ...
17968  5614689  2017-06-21 13:23:01.370      CA       ON            London
17969  5614801  2017-06-21 12:23:07.880      CA       ON  Saint Catharines
17970  5614909  2017-06-21 00:23:07.903      CA       ON            Whitby
17971  5614912  2017-06-21 11:23:07.953      CA       ON          Oakville
17972  5615006  2017-06-21 17:23:08.033      CA       ON          Oakville

       Latitude  Longitude  POI
0      43.49347  -80.49123  NaN
1      42.93990  -81.27090  NaN
2      43.57760  -80.22010  NaN
3      43.37160  -80.97730  NaN
4      43.37160  -80.97730  NaN
...         ...        ...  ...
17968  42.96110  -81.24310  NaN
17969  43.16440  -79.24560  NaN
17970  43.88730  -78.94220  NaN
17971  43.49340  -79.71260  NaN
17972  43.43090  -79.77670  NaN

[17973 rows x 8 columns]

<ipython-input-58-20f30de6a0a5>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["POI"]=np.nan
<ipython-input-58-20f30de6a0a5>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset["POI"]=min+1

           _ID                   TimeSt Country Province              City  \
0      4516516  2017-06-21 00:00:00.143      CA       ON          Waterloo
1      4516547  2017-06-21 18:00:00.193      CA       ON            London
2      4516550  2017-06-21 15:00:00.287      CA       ON            Guelph
3      4516600  2017-06-21 15:00:00.307      CA       ON         Stratford
4      4516613  2017-06-21 15:00:00.497      CA       ON         Stratford
...        ...                      ...     ...      ...               ...
17968  5614689  2017-06-21 13:23:01.370      CA       ON            London
17969  5614801  2017-06-21 12:23:07.880      CA       ON  Saint Catharines
17970  5614909  2017-06-21 00:23:07.903      CA       ON            Whitby
17971  5614912  2017-06-21 11:23:07.953      CA       ON          Oakville
17972  5615006  2017-06-21 17:23:08.033      CA       ON          Oakville

       Latitude  Longitude  POI
0      43.49347  -80.49123    3
1      42.93990  -81.27090    3
2      43.57760  -80.22010    3
3      43.37160  -80.97730    3
4      43.37160  -80.97730    3
...         ...        ...  ...
17968  42.96110  -81.24310    3
17969  43.16440  -79.24560    3
17970  43.88730  -78.94220    3
17971  43.49340  -79.71260    3
17972  43.43090  -79.77670    3

[17973 rows x 8 columns]